version: 2
jobs:
  build:
    docker:
      - image: python:3.8.3
      - image: postgres:10.1
        environment:
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            ./test.sh
