# Generated by Django 3.1.1 on 2020-09-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_a', models.IntegerField(unique=True)),
                ('id_b', models.IntegerField(unique=True)),
                ('colour', models.CharField(choices=[('black', 'black'), ('white', 'white')], default='white', max_length=64)),
            ],
        ),
    ]
