# Generated by Django 3.0.8 on 2020-10-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_a', models.IntegerField(unique=True)),
                ('id_b', models.IntegerField(unique=True)),
                ('hits', models.IntegerField(default=0)),
                ('colour', models.CharField(choices=[('black', 'black'), ('white', 'white')], default='white', max_length=64)),
            ],
        ),
    ]
